/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package finalproject;

/**
 *
 * @author yixu8827
 */
public class FormWindow extends javax.swing.JFrame {

    /**
     * Creates new form FormWindow
     */
    public FormWindow() {
        initComponents();
        Learn.setVisible(false);
        Test.setVisible(false);
        LearnPlant.setVisible(false);
        LearnAnimal.setVisible(false);
        TestPlant.setVisible(false);
        TestAnimal.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Intro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LearnButton = new javax.swing.JButton();
        TestButton = new javax.swing.JButton();
        Learn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        AnimalButton1 = new javax.swing.JButton();
        PlantsButton1 = new javax.swing.JButton();
        BackB1 = new javax.swing.JButton();
        Test = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AnimalButton2 = new javax.swing.JButton();
        PlantsButton2 = new javax.swing.JButton();
        BackB2 = new javax.swing.JButton();
        LearnAnimal = new javax.swing.JPanel();
        LAnimal = new javax.swing.JLabel();
        BackB3 = new javax.swing.JButton();
        LearnPlant = new javax.swing.JPanel();
        LPlants = new javax.swing.JLabel();
        BackB4 = new javax.swing.JButton();
        TestAnimal = new javax.swing.JPanel();
        TAnimal = new javax.swing.JLabel();
        BackB5 = new javax.swing.JButton();
        Mark1 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        Grade1 = new javax.swing.JLabel();
        TestPlant = new javax.swing.JPanel();
        TPlants = new javax.swing.JLabel();
        Back6 = new javax.swing.JButton();
        MarkB2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        Grade2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cells");

        LearnButton.setText("Learn");
        LearnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LearnButtonActionPerformed(evt);
            }
        });

        TestButton.setText("Test");
        TestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IntroLayout = new javax.swing.GroupLayout(Intro);
        Intro.setLayout(IntroLayout);
        IntroLayout.setHorizontalGroup(
            IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroLayout.createSequentialGroup()
                .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IntroLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(LearnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(TestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(IntroLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        IntroLayout.setVerticalGroup(
            IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IntroLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(IntroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LearnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TestButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        getContentPane().add(Intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 555, 440));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("What do you want to learn?");

        AnimalButton1.setText("Animal");
        AnimalButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButton1ActionPerformed(evt);
            }
        });

        PlantsButton1.setText("Plants");
        PlantsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantsButton1ActionPerformed(evt);
            }
        });

        BackB1.setText("Back");
        BackB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LearnLayout = new javax.swing.GroupLayout(Learn);
        Learn.setLayout(LearnLayout);
        LearnLayout.setHorizontalGroup(
            LearnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnLayout.createSequentialGroup()
                .addGroup(LearnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LearnLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3))
                    .addGroup(LearnLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(LearnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlantsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnimalButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackB1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(160, 160, 160))
        );
        LearnLayout.setVerticalGroup(
            LearnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(AnimalButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PlantsButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BackB1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(Learn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 555, -1));

        Test.setMaximumSize(new java.awt.Dimension(600, 600));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("What do you want to test?");

        AnimalButton2.setText("Animal");
        AnimalButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnimalButton2ActionPerformed(evt);
            }
        });

        PlantsButton2.setText("Plants");
        PlantsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlantsButton2ActionPerformed(evt);
            }
        });

        BackB2.setText("Back");
        BackB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TestLayout = new javax.swing.GroupLayout(Test);
        Test.setLayout(TestLayout);
        TestLayout.setHorizontalGroup(
            TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestLayout.createSequentialGroup()
                .addGroup(TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TestLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlantsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnimalButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BackB2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TestLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)))
                .addGap(160, 160, 160))
        );
        TestLayout.setVerticalGroup(
            TestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addGap(44, 44, 44)
                .addComponent(AnimalButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(PlantsButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BackB2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(Test, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        LAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/animal.png"))); // NOI18N

        BackB3.setText("Back");
        BackB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackB3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LearnAnimalLayout = new javax.swing.GroupLayout(LearnAnimal);
        LearnAnimal.setLayout(LearnAnimalLayout);
        LearnAnimalLayout.setHorizontalGroup(
            LearnAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnAnimalLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LAnimal)
                .addGap(0, 0, 0)
                .addComponent(BackB3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        LearnAnimalLayout.setVerticalGroup(
            LearnAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnAnimalLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(LearnAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAnimal, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BackB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(LearnAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 420));

        LPlants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plant.png"))); // NOI18N

        BackB4.setText("Back");
        BackB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackB4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LearnPlantLayout = new javax.swing.GroupLayout(LearnPlant);
        LearnPlant.setLayout(LearnPlantLayout);
        LearnPlantLayout.setHorizontalGroup(
            LearnPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnPlantLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LPlants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(BackB4))
        );
        LearnPlantLayout.setVerticalGroup(
            LearnPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LearnPlantLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(LearnPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackB4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LPlants, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(LearnPlant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/animalT.png"))); // NOI18N

        BackB5.setText("Back");
        BackB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackB5ActionPerformed(evt);
            }
        });

        Mark1.setText("Mark!");
        Mark1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mark1ActionPerformed(evt);
            }
        });

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        Grade1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Grade1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout TestAnimalLayout = new javax.swing.GroupLayout(TestAnimal);
        TestAnimal.setLayout(TestAnimalLayout);
        TestAnimalLayout.setHorizontalGroup(
            TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestAnimalLayout.createSequentialGroup()
                .addComponent(TAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TestAnimalLayout.createSequentialGroup()
                        .addGroup(TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField14)
                            .addComponent(jTextField15))
                        .addGap(83, 83, 83)
                        .addGroup(TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BackB5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Mark1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(TestAnimalLayout.createSequentialGroup()
                        .addGroup(TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextField10)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12)
                            .addComponent(jTextField13))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(TestAnimalLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(Grade1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        TestAnimalLayout.setVerticalGroup(
            TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestAnimalLayout.createSequentialGroup()
                .addGroup(TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TAnimal)
                    .addGroup(TestAnimalLayout.createSequentialGroup()
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TestAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestAnimalLayout.createSequentialGroup()
                                .addComponent(Mark1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BackB5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestAnimalLayout.createSequentialGroup()
                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grade1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        getContentPane().add(TestAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 440));

        TPlants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plantT.png"))); // NOI18N

        Back6.setText("Back");
        Back6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back6ActionPerformed(evt);
            }
        });

        MarkB2.setText("Mark!");
        MarkB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarkB2ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        Grade2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Grade2.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout TestPlantLayout = new javax.swing.GroupLayout(TestPlant);
        TestPlant.setLayout(TestPlantLayout);
        TestPlantLayout.setHorizontalGroup(
            TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestPlantLayout.createSequentialGroup()
                .addComponent(TPlants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TestPlantLayout.createSequentialGroup()
                        .addGroup(TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField7)
                            .addComponent(jTextField8))
                        .addGap(44, 44, 44)
                        .addGroup(TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Back6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MarkB2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(TestPlantLayout.createSequentialGroup()
                        .addGroup(TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(TestPlantLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(Grade2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        TestPlantLayout.setVerticalGroup(
            TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestPlantLayout.createSequentialGroup()
                .addGroup(TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TPlants)
                    .addGroup(TestPlantLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MarkB2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TestPlantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grade2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        getContentPane().add(TestPlant, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 440));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestButtonActionPerformed
        // TODO add your handling code here:
        Test.setVisible(true);
        Intro.setVisible(false); 
    }//GEN-LAST:event_TestButtonActionPerformed

    private void LearnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LearnButtonActionPerformed
        // TODO add your handling code here:
        Learn.setVisible(true);
        Intro.setVisible(false); 
    }//GEN-LAST:event_LearnButtonActionPerformed

    private void PlantsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantsButton1ActionPerformed
        // TODO add your handling code here:
        LearnPlant.setVisible(true);
        Learn.setVisible(false);
    }//GEN-LAST:event_PlantsButton1ActionPerformed

    private void BackB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackB1ActionPerformed
        // TODO add your handling code here:
        Intro.setVisible(true);
        Learn.setVisible(false); 
    }//GEN-LAST:event_BackB1ActionPerformed

    private void PlantsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlantsButton2ActionPerformed
        // TODO add your handling code here:
        TestPlant.setVisible(true);
        Test.setVisible(false); 
    }//GEN-LAST:event_PlantsButton2ActionPerformed

    private void BackB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackB2ActionPerformed
        // TODO add your handling code here:
        Intro.setVisible(true);
        Test.setVisible(false); 
    }//GEN-LAST:event_BackB2ActionPerformed

    private void AnimalButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalButton1ActionPerformed
        // TODO add your handling code here:
        LearnAnimal.setVisible(true);
        Learn.setVisible(false);

    }//GEN-LAST:event_AnimalButton1ActionPerformed

    private void BackB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackB4ActionPerformed
        // TODO add your handling code here:
        Learn.setVisible(true);
        LearnPlant.setVisible(false);
    }//GEN-LAST:event_BackB4ActionPerformed

    private void BackB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackB3ActionPerformed
        // TODO add your handling code here:
        Learn.setVisible(true);
        LearnAnimal.setVisible(false);
    }//GEN-LAST:event_BackB3ActionPerformed

    private void Back6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back6ActionPerformed
        // TODO add your handling code here:
        Grade2.setText(" ");
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        Test.setVisible(true);
        TestPlant.setVisible(false);
    }//GEN-LAST:event_Back6ActionPerformed

    private void MarkB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarkB2ActionPerformed
        // TODO add your handling code here:
        int grade=0;
        Grade2.setText(" ");
        
        if(jTextField1.getText().equalsIgnoreCase("vacuole"))
            grade++;
        if(jTextField2.getText().equalsIgnoreCase("cell wall"))
            grade++;
        if(jTextField3.getText().equalsIgnoreCase("cell membrane"))
            grade++;
        if(jTextField4.getText().equalsIgnoreCase("mitochondrion"))
            grade++;
        if(jTextField5.getText().equalsIgnoreCase("nucleus"))
            grade++;
        if(jTextField6.getText().equalsIgnoreCase("cytoplasm"))
            grade++;
        if(jTextField7.getText().equalsIgnoreCase("chloroplast"))
            grade++;
        if(jTextField8.getText().equalsIgnoreCase("vacuole"))
            grade++;
        
        if(grade<=2)
        Grade2.setText("Too Bad! You get "+grade+"/8 !");
        else if(grade<=4)
        Grade2.setText("Good! You get "+grade+"/8 !");
        else if(grade<=6)
        Grade2.setText("Great! You get "+grade+"/8 !");
        else if(grade==8)
        Grade2.setText("Great! You get all correct!");
        
            
    }//GEN-LAST:event_MarkB2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void BackB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackB5ActionPerformed
        // TODO add your handling code here:
        Grade1.setText(" ");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        Test.setVisible(true);
        TestAnimal.setVisible(false);
    }//GEN-LAST:event_BackB5ActionPerformed

    private void Mark1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mark1ActionPerformed
        // TODO add your handling code here:
        int grade=0;
        Grade1.setText(" ");
        
        if(jTextField9.getText().equalsIgnoreCase("vacuole"))
            grade++;
        if(jTextField10.getText().equalsIgnoreCase("cell membrane"))
            grade++;
        if(jTextField11.getText().equalsIgnoreCase("nucleus"))
            grade++;
        if(jTextField12.getText().equalsIgnoreCase("nucleus membrane"))
            grade++;
        if(jTextField13.getText().equalsIgnoreCase("DNA material"))
            grade++;
        if(jTextField14.getText().equalsIgnoreCase("cytoplasm"))
            grade++;
        if(jTextField15.getText().equalsIgnoreCase("mitochodria"))
            grade++;
        
        if(grade<=2)
        Grade1.setText("Too Bad! You get "+grade+"/7 !");
        else if(grade<=4)
        Grade1.setText("Good! You get "+grade+"/7 !");
        else if(grade<=6)
        Grade1.setText("Great! You get "+grade+"/7 !");
        else if(grade==7)
        Grade1.setText("Great! You get all correct!");
        
            
    }//GEN-LAST:event_Mark1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void AnimalButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnimalButton2ActionPerformed
        // TODO add your handling code here:
        TestAnimal.setVisible(true);
        Test.setVisible(false); 
    }//GEN-LAST:event_AnimalButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnimalButton1;
    private javax.swing.JButton AnimalButton2;
    private javax.swing.JButton Back6;
    private javax.swing.JButton BackB1;
    private javax.swing.JButton BackB2;
    private javax.swing.JButton BackB3;
    private javax.swing.JButton BackB4;
    private javax.swing.JButton BackB5;
    private javax.swing.JLabel Grade1;
    private javax.swing.JLabel Grade2;
    private javax.swing.JPanel Intro;
    private javax.swing.JLabel LAnimal;
    private javax.swing.JLabel LPlants;
    private javax.swing.JPanel Learn;
    private javax.swing.JPanel LearnAnimal;
    private javax.swing.JButton LearnButton;
    private javax.swing.JPanel LearnPlant;
    private javax.swing.JButton Mark1;
    private javax.swing.JButton MarkB2;
    private javax.swing.JButton PlantsButton1;
    private javax.swing.JButton PlantsButton2;
    private javax.swing.JLabel TAnimal;
    private javax.swing.JLabel TPlants;
    private javax.swing.JPanel Test;
    private javax.swing.JPanel TestAnimal;
    private javax.swing.JButton TestButton;
    private javax.swing.JPanel TestPlant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
